spring:
  application:
    name: food-administrative
  datasource:
    url: jdbc:mysql://localhost:3306/administrative?createDatabaseIfNotExist=true
    username: root
    password: foobar123
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

